# Generated by Django 5.2.7 on 2025-10-25 08:57

import django.utils.timezone
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_timestamp_inventorymovement_reserved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='inventory',
            name='low_stock_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reservation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='ttl_expires_at',
            field=models.DateTimeField(default=inventory.models.default_ttl),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('SHIP', 'Ship'), ('RESTOCK', 'Restock'), ('ADJUSTMENT', 'Adjustment'), ('WRITE_OFF', 'Write Off'), ('RETURN', 'Return')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'warehouse')},
        ),
    ]
