apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker
  namespace: eci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
      containers:
        - name: worker
          image: kalarenga76/eci-notification-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_URL
              value: amqp://apiuser:apipass@rabbitmq:5672/
            - name: RABBITMQ_EXCHANGE
              value: orders.x
            - name: RABBITMQ_QUEUE
              value: notifications.q
            - name: NOTIFY_ROUTING_KEYS
              value: order.confirmed,payment.succeeded,payment.failed
            - name: SMTP_HOST
              value: mailhog
            - name: SMTP_PORT
              value: "1025"
            - name: FROM_EMAIL
              value: no-reply@eci.local
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"