apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: eci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
        - name: api
          image: eci/payment:local
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "true"
            - name: ALLOWED_HOSTS
              value: "*"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: eci
spec:
  selector:
    app: payment-api
  ports:
    - port: 8000
      targetPort: 8000
