apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: eci
spec:
  replicas: 1
  selector:
    matchLabels: { app: catalog-api }
  template:
    metadata:
      labels: { app: catalog-api }
    spec:
      containers:
        - name: catalog
          image: eci/catalog:local                 # <-- your image tag
          imagePullPolicy: IfNotPresent
          # For dev Django: uncomment next 2 lines and remove gunicorn args if needed
          # command: ["python","manage.py","runserver"]
          # args: ["0.0.0.0:8000"]
          # For gunicorn (comment these if using runserver)
          command: ["gunicorn"]
          args: ["catalog.wsgi:application","-b","0.0.0.0:8000","-w","2","--timeout","60"]
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "mysql://catalog_user:S123pass@catalog-db:3306/catalog_db"
            - name: DJANGO_SETTINGS_MODULE
              value: "catalog.settings"
            - name: DEBUG
              value: "true"
          readinessProbe:
            tcpSocket: { port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket: { port: 8000 }
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: eci
spec:
  selector: { app: catalog-api }
  ports:
    - name: http
      port: 8000
      targetPort: 8000
