apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-mysql-pvc
  namespace: eci
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-mysql
  namespace: eci
spec:
  replicas: 1
  selector: { matchLabels: { app: payment-mysql } }
  template:
    metadata: { labels: { app: payment-mysql } }
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "payment_db"
            - name: MYSQL_USER
              value: "payment_user"
            - name: MYSQL_PASSWORD
              value: "S123pass"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: payment-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: payment-mysql
  namespace: eci
spec:
  selector: { app: payment-mysql }
  ports:
    - port: 3306
      targetPort: 3306
