# Generated by Django 5.2.7 on 2025-10-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymovement',
            old_name='timestamp',
            new_name='reserved_at',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='warehouse',
            field=models.CharField(max_length=100),
        ),
    ]
