# Generated by Django 5.2.7 on 2025-10-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='low_stock_threshold',
        ),
        migrations.AddField(
            model_name='inventory',
            name='threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='on_hand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('RESERVE', 'Reserve'), ('IN', 'Inbound'), ('OUT', 'Outbound'), ('RELEASE', 'Release'), ('SHIP', 'Ship'), ('RESTOCK', 'Restock'), ('ADJUSTMENT', 'Adjustment'), ('WRITE_OFF', 'Write Off'), ('RETURN', 'Return')], max_length=20),
        ),
    ]
